"""Run the command benchmark (bslm/commands.py) against the router.

    python -m bslm.commands_bench          writes COMMANDS_BENCHMARK.md

Per domain accuracy with the 80% bar; a domain under 80% is marked FAIL.
"""
import json
import re
import unicodedata
from collections import defaultdict
from pathlib import Path

from .commands import COMMANDS, WORK_INTENTS
from .infer import Parser

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "COMMANDS_BENCHMARK.md"
ARTICLES = r"^(?:the|a|an|at|on|in|to|for|my|στις|στη|στην|στο|στον|στα|τις|την|τη|τον|το|τα|για|σε|από)\s+"


def norm(v):
    v = "".join(c for c in unicodedata.normalize("NFD", v.lower().strip().strip(".,!?;")) if unicodedata.category(c) != "Mn")
    while True:
        n = re.sub(ARTICLES, "", v)
        if n == v:
            return v
        v = n


def slot_ok(expected, got):
    for k, want in expected.items():
        have = got.get(k)
        if have is None:
            return False
        w = want if isinstance(want, list) else [want]
        h = have if isinstance(have, list) else [have]
        if sorted(norm(x) for x in w) != sorted(norm(x) for x in h):
            return False
    return True


def domain(intent):
    if intent == "oos":
        return "out of scope"
    if intent.startswith("work.") or intent == "rule.set":
        return "work: " + intent
    return "everyday: " + intent.split(".")[0]


def training_texts():
    """Normalised training utterances, to measure how much of the benchmark the
    generator happens to produce verbatim (short generic commands mostly)."""
    f = ROOT / "data" / "train.jsonl"
    if not f.exists():
        return set()
    return {re.sub(r"[^a-z0-9 ]", "", json.loads(l)["text"].lower()).strip()
            for l in f.open(encoding="utf-8")}


def main():
    p = Parser()
    seen = training_texts()
    per = defaultdict(lambda: [0, 0, 0])      # intent ok, both ok, n
    misses = []
    leaked, clean_ok, clean_n = [], 0, 0
    for text, intent, slots in COMMANDS:
        r = p.parse(text)
        i_ok = r["intent"] == intent
        s_ok = slot_ok(slots, r["slots"])
        d = domain(intent)
        per[d][2] += 1
        per[d][0] += i_ok
        per[d][1] += i_ok and s_ok
        if re.sub(r"[^a-z0-9 ]", "", text.lower()).strip() in seen:
            leaked.append(text)
        else:
            clean_n += 1
            clean_ok += i_ok
        if not (i_ok and s_ok):
            misses.append((text, intent, r["intent"], r["confidence"], slots, r["slots"]))
    n = len(COMMANDS)
    ti = sum(v[0] for v in per.values())
    tb = sum(v[1] for v in per.values())

    rows = ["| domain | n | intent | intent and slots | bar |", "|---|---|---|---|---|"]
    fails, small = 0, 0
    for d, (i, b, k) in sorted(per.items()):
        ok = i / k >= 0.8
        if k < 5:
            # one miss in a domain of two or three commands is not evidence of
            # anything; the bar is only applied where it can be measured
            small += 1
            verdict = "n too small" if ok else "n too small, miss"
        else:
            fails += not ok
            verdict = "pass" if ok else "**FAIL**"
        rows.append(f"| {d} | {k} | {100*i/k:.0f}% | {100*b/k:.0f}% | {verdict} |")
    md = f"""# Command benchmark

{n} commands written by hand from the chat audit, in the author's own style,
never seen by the training templates. Generated by `python -m bslm.commands_bench`.

| | intent | intent and slots |
|---|---|---|
| **all commands** | **{100*ti/n:.1f}%** | {100*tb/n:.1f}% |
| commands that also occur verbatim in the generated training set ({len(leaked)}) | excluded below | |
| **clean subset, never seen in training ({clean_n})** | **{100*clean_ok/max(1,clean_n):.1f}%** | |

The verbatim overlap is unavoidable for short generic commands ("louder",
"good morning", "kill the timer"); the clean subset is the honest number.
Overlapping commands: {", ".join(f"`{t}`" for t in leaked) or "none"}.

Bar: every domain with at least five commands at 80% intent accuracy or
better. Below is a fail, not a rounding error. Domains with fewer than five
commands are reported but not judged ({small} of them); they need more
commands before the bar means anything.

{chr(10).join(rows)}

Work intents (routing, not execution): {"; ".join(f"`{k}` {v}" for k, v in WORK_INTENTS.items())}.

## Misses

{chr(10).join(f"- `{t}`  wanted **{w}** {json.dumps(ws, ensure_ascii=False)}  got **{g}** ({c:.2f}) {json.dumps(gs, ensure_ascii=False)}" for t, w, g, c, ws, gs in misses) or "- none"}
"""
    OUT.write_text(md, encoding="utf-8", newline="\n")
    print(f"{n} commands: intent {100*ti/n:.1f}%  both {100*tb/n:.1f}%  clean {100*clean_ok/max(1,clean_n):.1f}%  "
          f"domains failing the bar: {fails}  (too small to judge: {small})")
    print(f"written {OUT}")


if __name__ == "__main__":
    main()
