"""The command benchmark: how the author actually talks to an assistant.

Written by hand from the chat audit (his turns only, client names and
personal details replaced), never generated from the templates, so it is a
true held out test. Each entry: (command, expected intent, expected slots).
Slots are checked only where listed. English only, his style: lowercase,
short, imperative, sometimes a typo.
"""

COMMANDS = [
    # ---------------- everyday: time, timers, alarms ----------------
    ("timer 12 min", "timer.set", {"duration": "12 min"}),
    ("put a timer for the pasta, 9 minutes", "timer.set", {"duration": "9 minutes"}),
    ("how long left on the timer", "timer.query", {}),
    ("kill the timer", "timer.cancel", {}),
    ("wake me 6:15", "alarm.set", {"time": "6:15"}),
    ("alarm for tomorrow 7 am", "alarm.set", {"time": "7 am", "date": "tomorrow"}),
    ("no alarm tomorrow, i sleep in", "alarm.cancel", {}),
    ("what time is it in new york", "time.query", {"location": "new york"}),
    ("what day is it today", "time.query", {}),
    # ---------------- reminders, lists, notes ----------------
    ("remind me to send the invoice at 10", "reminder.create", {"task": "send the invoice", "time": "10"}),
    ("remind me tomorrow to call the accountant", "reminder.create", {"task": "call the accountant", "date": "tomorrow"}),
    ("dont let me forget to renew the domain on friday", "reminder.create", {"task": "renew the domain", "date": "friday"}),
    ("what do i have to do today", "reminder.list", {}),
    ("show my reminders", "reminder.list", {}),
    ("add coffee and milk to the list", "list.add", {"item": ["coffee", "milk"]}),
    ("put batteries on the shopping list", "list.add", {"item": "batteries", "list_name": "shopping list"}),
    ("whats on the shopping list", "list.read", {}),
    ("note: the server password is in the vault", "note.create", {}),
    ("write down that the meeting moved to thursday", "note.create", {"note": "the meeting moved to thursday"}),
    ("read my notes", "note.read", {}),
    # ---------------- calendar ----------------
    ("put a client call on friday at 11", "calendar.create", {"title": "client call", "date": "friday", "time": "11"}),
    ("add dentist tuesday 9:30 to the calendar", "calendar.create", {"title": "dentist", "date": "tuesday", "time": "9:30"}),
    ("what do i have tomorrow", "calendar.query", {"date": "tomorrow"}),
    ("am i free friday afternoon", "calendar.query", {}),
    ("when is my next meeting", "calendar.query", {}),
    # ---------------- weather ----------------
    ("is it going to rain today", "weather.query", {"date": "today"}),
    ("weather in thessaloniki this weekend", "weather.query", {"location": "thessaloniki"}),
    ("do i need a jacket tonight", "weather.query", {"date": "tonight"}),
    ("how hot is it outside", "weather.query", {}),
    # ---------------- music, volume ----------------
    ("play some jazz", "music.play", {"genre": "jazz"}),
    ("play hotel california", "music.play", {"song": "hotel california"}),
    ("put on my workout playlist", "music.play", {"playlist": "my workout playlist"}),
    ("next", "music.control", {}),
    ("pause", "music.control", {}),
    ("what song is this", "music.control", {}),
    ("louder", "volume.set", {}),
    ("volume 30", "volume.set", {"level": "30"}),
    ("too loud", "volume.set", {}),
    # ---------------- home ----------------
    ("lights off", "light.control", {}),
    ("turn on the kitchen light", "light.control", {"room": "kitchen"}),
    ("dim the living room", "light.control", {"room": "living room"}),
    ("bedroom lights warm white", "light.control", {"room": "bedroom", "color": "warm white"}),
    ("turn off the tv", "device.control", {"device": "tv"}),
    ("is the boiler on", "device.control", {"device": "boiler"}),
    ("switch on the ac", "device.control", {"device": "ac"}),
    # ---------------- maths, units ----------------
    ("what is 17 percent of 3200", "math.calculate", {"expression": "17 percent of 3200"}),
    ("1450 divided by 12", "math.calculate", {"expression": "1450 divided by 12"}),
    ("40 kilos in pounds", "unit.convert", {"amount": "40", "unit_from": "kilos", "unit_to": "pounds"}),
    ("how many km is 60 miles", "unit.convert", {"amount": "60", "unit_from": "miles", "unit_to": "km"}),
    ("250 euros to dollars", "unit.convert", {"amount": "250", "unit_from": "euros", "unit_to": "dollars"}),
    # ---------------- info, search, translate, news ----------------
    ("google cheap flights to berlin in october", "search.web", {"query": "cheap flights to berlin in october"}),
    ("look up how to fix a leaking tap", "search.web", {"query": "how to fix a leaking tap"}),
    ("search online dont guess: raspberry pi 5 price", "search.web", {}),
    ("how do you say good evening in italian", "translate", {"phrase": "good evening", "language": "italian"}),
    ("translate thank you very much to german", "translate", {"phrase": "thank you very much", "language": "german"}),
    ("whats the news", "news.query", {}),
    ("any news on the economy", "news.query", {"topic": "the economy"}),
    # ---------------- comms, navigation ----------------
    ("text maria i am 10 minutes late", "message.send", {"person": "maria", "content": "i am 10 minutes late"}),
    ("tell nick the invoice is sent", "message.send", {"person": "nick", "content": "the invoice is sent"}),
    ("call my brother", "call.make", {"person": "my brother"}),
    ("ring the accountant", "call.make", {"person": "the accountant"}),
    ("directions to the airport", "navigation.route", {"location": "the airport"}),
    ("how do i get to piraeus", "navigation.route", {"location": "piraeus"}),
    ("is there traffic to the office", "navigation.route", {"location": "the office"}),
    # ---------------- small talk, assistant ----------------
    ("hey", "smalltalk.greet", {}),
    ("good morning", "smalltalk.greet", {}),
    ("thanks a lot", "smalltalk.thanks", {}),
    ("perfect, thanks", "smalltalk.thanks", {}),
    ("ok bye", "smalltalk.bye", {}),
    ("what can you do", "assistant.capabilities", {}),
    ("say that again", "assistant.repeat", {}),
    ("never mind", "assistant.cancel", {}),
    ("forget it", "assistant.cancel", {}),
    # ---------------- work: code ----------------
    ("fix the bug on the checkout page", "work.code", {"target": "the checkout page"}),
    ("add pagination to the trade log", "work.code", {"target": "the trade log"}),
    ("the form does not submit on mobile, fix it", "work.code", {}),
    ("implement the stop loss so we stop paying fees", "work.code", {}),
    ("make the header sticky", "work.code", {"target": "the header"}),
    ("refactor the tokenizer, its too slow", "work.code", {"target": "the tokenizer"}),
    ("write a script that renames the files by date", "work.code", {}),
    ("the dashboard writes 50 times a minute, make it one write per tick", "work.code", {}),
    ("build the landing page for the saas", "work.code", {"target": "the landing page"}),
    ("patch the exporter like we discussed", "work.code", {}),
    # ---------------- work: review and checks ----------------
    ("check again if its done", "work.review", {}),
    ("audit the signals for bugs, no trades are being made", "work.review", {}),
    ("make a full disk check, what can be cleaned", "work.review", {}),
    ("double check the numbers, holdings and equity dont align", "work.review", {}),
    ("verify the deploy went through", "work.review", {}),
    ("do another pass on the whole project", "work.review", {}),
    ("check for bugs on the models", "work.review", {}),
    ("is the pi still running the bot", "work.status", {}),
    ("what is left to decide", "work.status", {}),
    ("where are we with the site", "work.status", {}),
    ("did the training finish", "work.status", {}),
    ("give me the status of everything", "work.status", {}),
    # ---------------- work: research and explanations ----------------
    ("explain what squirreltemp is", "work.research", {"topic": "squirreltemp"}),
    ("what is the difference between rag and fine tuning", "work.research", {}),
    ("should we move to the binance demo environment or stay", "work.research", {}),
    ("educate me on small language models", "work.research", {"topic": "small language models"}),
    ("compare viva and stripe fees for a 20 euro product", "work.research", {}),
    ("why is there a positive pnl when we lost money", "work.research", {}),
    ("give me 15 cpus close to a xeon gold 6242 from old to new", "work.research", {}),
    ("is cryptoquant free trial useful for the bot", "work.research", {}),
    # ---------------- work: writing ----------------
    ("write an email to the client that the site is ready", "work.write", {"person": "the client"}),
    ("prepare a shorter message, its for sms", "work.write", {}),
    ("draft a proposal for the booking platform", "work.write", {}),
    ("rewrite this in greek, formal", "work.write", {}),
    ("reply to the recruiter that i am available from october", "work.write", {"person": "the recruiter"}),
    ("write the linkedin post about the launch", "work.write", {}),
    ("make an md document of your findings in the project", "work.write", {}),
    # ---------------- work: files, system, cleanup ----------------
    ("delete the temp folders and the msi cache", "work.files", {}),
    ("uninstall ollama completely and remove the installer", "work.files", {}),
    ("move the games to the backup disk", "work.files", {}),
    ("clean up my pc, i want space back", "work.files", {}),
    ("zip the project and put it on the desktop", "work.files", {}),
    ("what is taking space on drive c", "work.files", {}),
    ("remove the dead updaters and installers", "work.files", {}),
    # ---------------- work: deploy and ops ----------------
    ("deploy", "work.ops", {}),
    ("restart the server", "work.ops", {}),
    ("push it live", "work.ops", {}),
    ("start the training on the other pc", "work.ops", {}),
    ("stop the current training and restart with 2 more workers", "work.ops", {}),
    ("renew the ssl on the store", "work.ops", {}),
    ("back up the database before you touch anything", "work.ops", {}),
    # ---------------- work: business ----------------
    ("prepare a quote for the events platform, phase a only", "work.business", {}),
    ("what should i charge for a 5 page site", "work.business", {}),
    ("the client wants the domain under his name, what do we do", "work.business", {}),
    ("send the invoice for august", "work.business", {}),
    ("how much did we make this month", "work.business", {}),
    ("is the saas worth it at 20 euros with these fees", "work.business", {}),
    # ---------------- rules for the assistant ----------------
    ("never use dashes", "rule.set", {}),
    ("from now on be terse", "rule.set", {}),
    ("dont question me again, just do it", "rule.set", {}),
    ("always search online before you answer", "rule.set", {}),
    ("dont touch the raspberry", "rule.set", {}),
    ("remember that i commute by scooter", "rule.set", {}),
    ("stop suggesting microphones and text to speech", "rule.set", {}),
    ("only english from now on", "rule.set", {}),
    # ---------------- out of scope ----------------
    ("write me a poem about the sea", "oos", {}),
    ("who is the prime minister of greece", "oos", {}),
    ("tell me a story about dragons", "oos", {}),
    ("what is the meaning of life", "oos", {}),
    ("asdf qwer zxcv", "oos", {}),
    ("μπλα μπλα μπλα", "oos", {}),
]

WORK_INTENTS = {
    "work.code": "a change to code or a site: fix, add, build, implement, refactor",
    "work.review": "check, audit, verify, pass over, double check",
    "work.status": "where are we, is it done, what is left",
    "work.research": "explain, compare, educate, should we, why is",
    "work.write": "draft an email, message, proposal, post, document",
    "work.files": "delete, uninstall, move, clean up, what takes space",
    "work.ops": "deploy, restart, push live, start or stop a job, backup",
    "work.business": "quote, price, invoice, client situation, revenue",
    "rule.set": "an instruction about how the assistant should behave, saved to the soul",
}
