"""Templates plus a lexical variation layer.

[markers] in square brackets are swapped for a synonym before slot filling,
so a handful of templates expands into thousands of distinct surface forms.
This is the single biggest lever on how well the model generalises: the model
can only learn that "kill", "scrap" and "cancel" mean the same thing if it has
seen them in the same slot.
{slots} in curly braces are the labelled spans.
"""

LEX = {
    # --- english ---------------------------------------------------------
    "start": {"en": ["set", "start", "put on", "kick off", "begin", "run",
                     "fire up", "give me", "get me", "make", "create", "add"],
              "el": ["βάλε", "ξεκίνα", "άρχισε", "φτιάξε", "δώσε μου", "ρύθμισε",
                     "όρισε", "βάλε μου", "ξεκίνησε"]},
    "cancel": {"en": ["cancel", "stop", "kill", "scrap", "delete", "remove",
                      "drop", "clear", "turn off", "forget", "get rid of",
                      "call off", "wipe", "bin"],
               "el": ["ακύρωσε", "σταμάτα", "σβήσε", "διέγραψε", "κόψε", "άκυρο",
                      "βγάλε", "ξέχνα", "τερμάτισε", "κλείσε", "πέταξε"]},
    "read": {"en": ["read", "read out", "read me", "show", "show me", "list",
                    "tell me", "give me", "go through", "pull up", "bring up",
                    "what is on", "what have I got on"],
             "el": ["διάβασε", "διάβασέ μου", "δείξε", "δείξε μου", "πες μου",
                    "βγάλε", "άνοιξε", "φέρε", "τι έχω σε", "για δες"]},
    "add": {"en": ["add", "put", "stick", "throw", "chuck", "write", "note",
                   "jot", "shove", "drop", "slap", "append"],
            "el": ["πρόσθεσε", "βάλε", "γράψε", "ρίξε", "πέταξε", "σημείωσε",
                   "καταχώρησε", "βάλε μου", "συμπλήρωσε"]},
    "play": {"en": ["play", "put on", "chuck on", "throw on", "start", "blast",
                    "spin", "stick on", "fire up", "queue up", "stream"],
             "el": ["βάλε", "παίξε", "ρίξε", "ξεκίνα", "άνοιξε", "βάλε μου",
                    "παίξε μου", "ανέβασε"]},
    "call": {"en": ["call", "phone", "dial", "ring", "ring up", "get hold of",
                    "reach", "buzz", "get on the phone"],
             "el": ["πάρε", "κάλεσε", "τηλεφώνησε", "πάρε τηλέφωνο", "βρες",
                    "χτύπα", "πάρε στο κινητό"]},
    "calc": {"en": ["calculate", "work out", "figure out", "compute", "what is",
                    "how much is", "do the maths on", "add up", "solve",
                    "give me", "tell me"],
             "el": ["υπολόγισε", "πόσο κάνει", "πόσο είναι", "βγάλε", "κάνε",
                    "λύσε", "πες μου πόσο κάνει", "βρες πόσο κάνει"]},
    "find": {"en": ["search for", "google", "look up", "find", "find me",
                    "search the web for", "dig up", "check", "look into",
                    "show me", "bring me"],
             "el": ["ψάξε", "ψάξε για", "αναζήτησε", "βρες", "βρες μου",
                    "γκούγκλαρε", "δες", "τσέκαρε", "κοίτα για"]},
    "remind": {"en": ["remind me to", "nudge me to", "ping me to", "poke me to",
                      "prompt me to", "don't let me forget to",
                      "make sure I", "give me a nudge to"],
               "el": ["θύμισέ μου", "να μου θυμίσεις", "μη με αφήσεις να ξεχάσω",
                      "φρόντισε να", "χτύπα μου να", "πες μου να"]},
    "wake": {"en": ["wake me up", "get me up", "wake me", "buzz me", "rouse me",
                    "have me up", "knock me up"],
             "el": ["ξύπνα με", "σήκωσέ με", "να με ξυπνήσεις", "ξύπνησέ με"]},
    "turn_on": {"en": ["turn on", "switch on", "put on", "fire up", "start up",
                       "power on", "get going", "flip on", "boot up"],
                "el": ["άναψε", "άνοιξε", "βάλε μπρος", "ενεργοποίησε",
                       "ξεκίνα", "άναψέ μου"]},
    "turn_off": {"en": ["turn off", "switch off", "shut off", "kill", "cut",
                        "power down", "shut down", "flip off", "put out"],
                 "el": ["σβήσε", "κλείσε", "απενεργοποίησε", "κόψε", "σταμάτα"]},
    "sched": {"en": ["schedule", "book", "pencil in", "block out", "set up",
                     "put in", "stick in", "slot in", "arrange", "line up"],
              "el": ["κλείσε", "κανόνισε", "βάλε", "καταχώρησε", "όρισε",
                     "προγραμμάτισε", "σημείωσε"]},
    "send": {"en": ["send", "text", "message", "drop", "shoot", "fire off",
                    "write", "ping"],
             "el": ["στείλε", "γράψε", "πέτα", "ρίξε", "στείλε μου"]},
    "go": {"en": ["navigate to", "get me to", "take me to", "directions to",
                  "route to", "how do I get to", "how do I drive to",
                  "guide me to", "point me to"],
           "el": ["πλοήγηση", "πήγαινέ με", "οδηγίες για", "πώς πάω",
                  "πώς φτάνω", "δείξε μου τον δρόμο για", "βγάλε με"]},
    "want": {"en": ["I want to", "I would like to", "I need to", "I fancy",
                    "I feel like", "let me"],
             "el": ["θέλω να", "θα ήθελα να", "έχω όρεξη να", "άσε με να"]},
    "whats": {"en": ["what is", "what's", "tell me", "give me", "how is",
                     "any idea about", "do you know"],
              "el": ["τι", "πες μου", "δώσε μου", "ξέρεις", "για πες"]},
    "fix": {"en": ["fix", "repair", "sort out", "debug", "patch", "correct", "solve", "handle"],
            "el": ["φτιάξε", "διόρθωσε", "λύσε"]},
    "buildv": {"en": ["build", "implement", "create", "add", "make", "code", "develop", "set up", "wire", "write"],
               "el": ["φτιάξε", "υλοποίησε", "πρόσθεσε", "γράψε"]},
    "check": {"en": ["check", "verify", "audit", "review", "double check", "inspect", "go over", "confirm", "test", "validate", "look at"],
              "el": ["έλεγξε", "τσέκαρε", "επιβεβαίωσε", "δες"]},
    "explain": {"en": ["explain", "educate me on", "walk me through", "tell me about", "break down", "clarify", "what is", "what are", "how does", "why is", "compare"],
                "el": ["εξήγησε", "πες μου για", "τι είναι", "γιατί"]},
    "draft": {"en": ["write", "draft", "prepare", "compose", "put together", "rewrite", "reply to", "answer", "make"],
              "el": ["γράψε", "ετοίμασε", "σύνταξε", "απάντησε"]},
    "delete": {"en": ["delete", "remove", "uninstall", "clean up", "clear", "wipe", "get rid of", "purge"],
               "el": ["σβήσε", "διέγραψε", "απεγκατέστησε", "καθάρισε"]},
    "deploy": {"en": ["deploy", "push", "ship", "release", "publish", "go live with", "roll out"],
               "el": ["ανέβασε", "κάνε deploy", "δημοσίευσε"]},
    "restartv": {"en": ["restart", "reboot", "start", "stop", "kill", "relaunch", "resume", "pause"],
                 "el": ["επανεκκίνησε", "ξεκίνα", "σταμάτα"]},
    "never": {"en": ["never", "do not", "dont", "don't", "stop", "no more", "quit"],
              "el": ["ποτέ", "μη", "μην", "σταμάτα να"]},
    "always": {"en": ["always", "from now on", "every time", "by default", "going forward", "in the future"],
               "el": ["πάντα", "από εδώ και πέρα", "κάθε φορά"]},

}

TEMPLATES = {
    "timer.set": {
        "en": ["[start] a timer for {duration}", "[start] a {duration} timer",
               "timer for {duration}", "{duration} timer",
               "[start] timer {duration}", "[wake] in {duration}",
               "buzz me in {duration}", "count down {duration}",
               "countdown of {duration}", "[start] the countdown for {duration}",
               "ping me in {duration}", "let me know in {duration}",
               "tell me when {duration} is up", "[start] counting {duration}",
               "I need a timer for {duration}", "[want] a timer of {duration}",
               "give it {duration} then tell me", "alert me in {duration}"],
        "el": ["[start] χρονόμετρο για {duration}", "[start] ένα χρονόμετρο {duration}",
               "χρονόμετρο {duration}", "χρονόμετρο για {duration}",
               "[start] αντίστροφη μέτρηση {duration}", "μέτρα {duration}",
               "χρονομέτρησε {duration}", "χτύπα μου σε {duration}",
               "ειδοποίησέ με σε {duration}", "πες μου όταν περάσουν {duration}",
               "θέλω χρονόμετρο {duration}", "[start] να μετράς {duration}",
               "σε {duration} να με ειδοποιήσεις", "βάλε {duration} στο χρονόμετρο"],
    },
    "timer.cancel": {
        "en": ["[cancel] the timer", "[cancel] my timer", "[cancel] that timer",
               "[cancel] the countdown", "[cancel] that countdown",
               "[cancel] counting", "stop counting down", "no more timer",
               "I don't need the timer any more", "the timer can go",
               "[cancel] the timer I set"],
        "el": ["[cancel] το χρονόμετρο", "[cancel] την αντίστροφη μέτρηση",
               "[cancel] το χρονόμετρο που έβαλα", "σταμάτα να μετράς",
               "σταμάτα το να μετράει", "δε θέλω άλλο το χρονόμετρο",
               "τέλος το χρονόμετρο", "[cancel] τη μέτρηση"],
    },
    "timer.query": {
        "en": ["how much time is left", "how long on the timer",
               "how much longer", "what is left on my timer", "time remaining",
               "how long until the timer goes off", "where is the timer at",
               "how much is left on the countdown", "is the timer nearly done"],
        "el": ["πόσος χρόνος μένει", "πόση ώρα έμεινε", "πόσο ακόμα",
               "τι λέει το χρονόμετρο", "πόσο μένει στο χρονόμετρο",
               "πότε χτυπάει το χρονόμετρο", "πόσο απομένει"],
    },
    "alarm.set": {
        "en": ["[start] an alarm for {time}", "[wake] at {time}",
               "alarm at {time}", "[start] an alarm for {time} {date}",
               "[wake] at {time} {date}", "I need to be up at {time}",
               "[start] my alarm to {time}", "alarm {date} at {time}",
               "[wake] {date} at {time}", "I am getting up at {time} {date}",
               "alarm for {time} please", "[start] the alarm {time}"],
        "el": ["[start] ξυπνητήρι για {time}", "[wake] {time}",
               "ξυπνητήρι στις {time}", "[start] ξυπνητήρι {date} {time}",
               "θέλω να ξυπνήσω {time}", "[start] το ξυπνητήρι για {time}",
               "ξυπνητήρι για {date} {time}", "[wake] {date} {time}",
               "πρέπει να σηκωθώ {time}", "ξυπνητήρι {time}"],
    },
    "alarm.cancel": {
        "en": ["[cancel] my alarm", "[cancel] the alarm", "[cancel] the alarm for {time}",
               "no alarm tomorrow", "I don't need the alarm",
               "[cancel] the morning alarm", "let me sleep in tomorrow"],
        "el": ["[cancel] το ξυπνητήρι", "[cancel] το ξυπνητήρι για {time}",
               "μη με ξυπνήσεις αύριο", "δε θέλω ξυπνητήρι",
               "[cancel] το πρωινό ξυπνητήρι", "θα κοιμηθώ ως αργά"],
    },
    "reminder.create": {
        "en": ["remind me {date} to {task}", "remind me at {time} to {task}", "remind me {date} at {time} to {task}", "{date}, remind me to {task}", "[remind] {task}", "[remind] {task} {date}",
               "[remind] {task} at {time}", "[remind] {task} {date} at {time}",
               "[start] a reminder to {task}", "I need to remember to {task} {date}",
               "reminder {task} {date}", "note to self {task}",
               "[remind] {task} before I forget",
               "[start] a reminder for {date} to {task}",
               "make a reminder to {task} {date}"],
        "el": ["[remind] {task}", "[remind] {task} {date}",
               "[remind] {task} στις {time}", "[remind] {task} {date} στις {time}",
               "[start] υπενθύμιση {task}", "μην ξεχάσω {task} {date}",
               "πρέπει να θυμηθώ {task}", "υπενθύμιση {task} {date}",
               "[start] μια υπενθύμιση για {date} {task}"],
    },
    "reminder.list": {
        "en": ["what are my reminders", "[read] my reminders",
               "what do I have to do {date}", "[read] the reminder list",
               "what am I forgetting", "what is on my todo",
               "what have I got to do {date}", "run me through my reminders",
               "any reminders {date}"],
        "el": ["τι υπενθυμίσεις έχω", "[read] τις υπενθυμίσεις μου",
               "τι έχω να κάνω {date}", "[read] τη λίστα με τις υπενθυμίσεις",
               "τι ξεχνάω", "έχω τίποτα να κάνω {date}",
               "για πες τι έχω να κάνω"],
    },
    "calendar.create": {
        "en": ["[add] {title} to my calendar {date} at {time}",
               "[sched] {title} {date}", "[sched] {title} for {date} at {time}",
               "[add] {title} in the calendar at {time}",
               "[start] an event {title} {date}",
               "new appointment {title} {date} {time}",
               "I have {title} {date} at {time}",
               "[sched] {title} with {person} {date}",
               "[add] {title} {date} at {time} to the diary",
               "put {title} down for {date}"],
        "el": ["[add] {title} στο ημερολόγιο {date} στις {time}",
               "[sched] {title} {date}", "[sched] {title} {date} στις {time}",
               "νέο ραντεβού {title} {date} {time}",
               "έχω {title} {date} στις {time}", "[add] {title} {date}",
               "[sched] {title} με {person} {date}",
               "γράψε {title} για {date} στις {time}"],
    },
    "calendar.query": {
        "en": ["what is on my calendar {date}", "what do I have {date}",
               "am I free {date}", "am I busy {date}",
               "[read] my schedule for {date}", "when is my next meeting",
               "what is my next appointment", "do I have anything at {time}",
               "have I got anything on {date}", "what does {date} look like",
               "is my diary clear {date}"],
        "el": ["τι έχω στο ημερολόγιο {date}", "τι ραντεβού έχω {date}",
               "είμαι ελεύθερος {date}", "[read] το πρόγραμμά μου για {date}",
               "πότε είναι το επόμενο ραντεβού", "τι έχω {date}",
               "έχω τίποτα {date}", "πώς είναι η {date} μου",
               "είμαι μπλοκαρισμένος {date}"],
    },
    "weather.query": {
        "en": ["is it going to rain {date}", "is it raining", "rain {date}?", "will it be sunny {date}", "chance of rain {date}", "umbrella {date}?", "[whats] the weather like", "[whats] the weather in {location}",
               "will it rain {date}", "weather {location} {date}",
               "do I need an umbrella {date}", "how hot is it in {location}",
               "is it cold outside", "temperature in {location}",
               "[whats] the forecast for {date}", "will it snow in {location}",
               "is it going to rain in {location} {date}",
               "how is it looking outside {date}", "is it sunny in {location}",
               "should I take a jacket {date}", "how windy is it {location}"],
        "el": ["τι καιρό κάνει", "τι καιρό κάνει {location}",
               "θα βρέξει {date}", "καιρός {location} {date}",
               "χρειάζομαι ομπρέλα {date}", "πόσο κάνει {location}",
               "κάνει κρύο έξω", "πρόγνωση για {date}", "θα χιονίσει {location}",
               "θα ρίξει βροχή {location} {date}", "έχει ήλιο {location}",
               "να πάρω μπουφάν {date}", "τι καιρό θα κάνει {date}",
               "φυσάει {location}"],
    },
    "music.play": {
        "en": ["[play] {song}", "{song} please", "[play] {song} again", "[play] {artist} songs", "{artist} please", "[play] {song}", "[play] {song} by {artist}", "[play] {artist}",
               "[play] some {genre}", "[play] my {playlist}", "shuffle {playlist}",
               "[want] listen to {artist}", "[play] {genre}",
               "[play] {song} on the speakers", "some {genre} please",
               "[play] a bit of {genre}", "[play] anything by {artist}",
               "[want] hear {song}", "[play] the {playlist}"],
        "el": ["[play] {song}", "[play] {artist}", "[play] λίγο {genre}",
               "[play] {playlist}", "[want] ακούσω {artist}",
               "[play] μουσική {genre}", "[play] {song} στα ηχεία",
               "λίγο {genre} παρακαλώ", "[play] κάτι από {artist}",
               "[want] ακούσω {song}", "[play] τη λίστα {playlist}"],
    },
    "music.control": {
        "en": ["pause", "pause it", "pause the song", "unpause", "play", "resume", "pause the music", "[cancel] the music", "next song", "skip this",
               "skip this track", "previous track", "resume the music",
               "play it again", "go back a song", "mute the music",
               "what song is this", "shut the music off", "hush the music",
               "who sings this", "turn the music back on", "keep playing"],
        "el": ["σταμάτα τη μουσική", "παύση", "επόμενο τραγούδι",
               "άλλαξε τραγούδι", "προηγούμενο", "συνέχισε τη μουσική",
               "ξαναβάλε το", "τι τραγούδι είναι αυτό", "σίγαση",
               "[cancel] τη μουσική", "πάμε στο επόμενο", "ποιος το τραγουδάει",
               "βάλε το ξανά", "άσε το να παίζει"],
    },
    "volume.set": {
        "en": ["[start] the volume to {level}", "volume {level}", "turn it up",
               "turn it down", "louder", "quieter", "volume up", "volume down",
               "make it louder", "[start] volume at {level} percent",
               "crank it up", "crank the volume to {level}", "bit louder",
               "bit quieter", "drop the volume", "bump the volume to {level}",
               "too loud", "too quiet"],
        "el": ["[start] την ένταση στο {level}", "ένταση {level}", "δυνάμωσέ το",
               "χαμήλωσέ το", "πιο δυνατά", "πιο σιγά", "αύξησε την ένταση",
               "μείωσε την ένταση", "[start] ένταση {level} τοις εκατό",
               "δυνάμωσε λίγο", "χαμήλωσε λίγο", "πολύ δυνατά", "πολύ σιγά",
               "ανέβασε την ένταση στο {level}", "κατέβασε τον ήχο"],
    },
    "light.control": {
        "en": ["[turn_on] the lights", "[turn_off] the lights in the {room}",
               "[turn_on] the {room} light", "dim the lights in the {room}",
               "[start] the {room} lights to {color}", "lights {color}",
               "brightness {brightness} in the {room}", "[turn_off] the lights",
               "[turn_off] the light in the {room}", "make the {room} lights {color}",
               "[turn_on] the light in the {room}", "lights on in the {room}",
               "lights off in the {room}", "[start] the lights to {brightness} percent",
               "I want the {room} lights {color}"],
        "el": ["[turn_on] τα φώτα", "[turn_off] τα φώτα στην {room}",
               "[turn_on] το φως στο {room}", "χαμήλωσε τα φώτα στο {room}",
               "[start] τα φώτα {color}", "φώτα {color}",
               "φωτεινότητα {brightness} στο {room}", "[turn_off] όλα τα φώτα",
               "[turn_off] το φως στην {room}", "θέλω τα φώτα {color} στο {room}",
               "φώτα στο {room}", "[turn_on] φώτα στην {room}"],
    },
    "device.control": {
        "en": ["[turn_on] the {device}", "[turn_off] the {device}", "{device} on", "{device} off", "[turn_on] the ac", "[turn_off] the ac", "[turn_on] the {device}", "[turn_off] the {device}",
               "[turn_on] the {device} in the {room}", "[turn_off] the {device} in the {room}",
               "is the {device} on", "[turn_on] the {device} please",
               "[turn_off] that {device}", "get the {device} going",
               "I left the {device} on", "can you [turn_off] the {device}"],
        "el": ["[turn_on] {device}", "[turn_off] {device}", "[turn_on] τη {device}",
               "[turn_off] τη {device}", "είναι ανοιχτή η {device}",
               "[turn_off] {device} στο {room}", "[turn_on] {device} στο {room}",
               "άφησα ανοιχτό {device}", "μπορείς να [turn_off] {device}"],
    },
    "list.add": {
        "en": ["[add] {item} to my {list_name}", "[add] {item} on the {list_name}",
               "[add] {item} to the list", "I need to buy {item}",
               "we are out of {item}", "[add] {item} and {item} to the {list_name}",
               "remember to buy {item}", "[add] {item} to the shopping",
               "we need {item}", "buy {item}", "{item} for the {list_name}",
               "[add] {item} and {item} to the list"],
        "el": ["[add] {item} στη {list_name}", "[add] {item} στη λίστα",
               "πρέπει να πάρω {item}", "ξεμείναμε από {item}",
               "[add] {item} στα ψώνια", "θέλουμε {item}",
               "[add] {item} και {item} στη λίστα", "αγόρασε {item}",
               "{item} για τη {list_name}"],
    },
    "list.read": {
        "en": ["what is on my {list_name}", "[read] my {list_name}",
               "[read] the shopping list", "what do I need to buy",
               "[read] everything on my {list_name}", "what is on the list",
               "how does the {list_name} look", "run through the {list_name}",
               "what am I buying"],
        "el": ["τι έχω στη {list_name}", "[read] τη {list_name}",
               "[read] τη λίστα με τα ψώνια", "τι πρέπει να αγοράσω",
               "τι έχει η λίστα", "τι γράφει η {list_name}",
               "για διάβασε τη λίστα", "τι ψώνια έχω"],
    },
    "note.create": {
        "en": ["make a note that {note}", "note down that {note}", "take note: {note}", "write down: {note}", "put in my notes that {note}", "note for later: {note}", "write down that {note}", "write this down: {note}", "note this: {note}", "keep a note: {note}", "jot this down {note}", "take a note {note}", "note that {note}", "[add] down {note}",
               "make a note {note}", "save this note {note}", "remember that {note}",
               "[add] this down {note}", "keep a note that {note}",
               "for the record {note}", "log that {note}"],
        "el": ["κράτα σημείωση {note}", "σημείωσε {note}", "[add] {note}",
               "κράτα ότι {note}", "αποθήκευσε σημείωση {note}",
               "να θυμάσαι ότι {note}", "γράψε κάπου ότι {note}",
               "κράτα το εξής {note}"],
    },
    "note.read": {
        "en": ["[read] my notes", "what notes do I have", "[read] the last note",
               "open my notes", "what have I noted down", "what did I write down",
               "anything in my notes", "go through my notes",
               "what have I got in my notes", "what is written in my notes",
               "[read] what I wrote", "anything I noted", "[read] my saved notes"],
        "el": ["[read] τις σημειώσεις μου", "τι σημειώσεις έχω",
               "[read] την τελευταία σημείωση", "τι έχω σημειώσει",
               "τι έγραψα", "άνοιξε τις σημειώσεις", "έχω τίποτα σημειωμένο",
               "τι έχω γράψει", "[read] τι έχω σημειώσει", "τι λένε οι σημειώσεις μου"],
    },
    "message.send": {
        "en": ["[send] a message to {person} saying {content}",
               "[send] {person} {content}", "[send] {person} that {content}",
               "tell {person} {content}", "[send] {person} a text saying {content}",
               "whatsapp {person} {content}", "email {person} saying {content}",
               "[send] {person} a line saying {content}",
               "let {person} know that {content}", "[send] word to {person} that {content}"],
        "el": ["[send] μήνυμα {person} ότι {content}", "[send] {person} {content}",
               "πες {person} ότι {content}", "[send] μέιλ {person} ότι {content}",
               "ενημέρωσε {person} ότι {content}",
               "[send] ένα μήνυμα {person} και πες ότι {content}"],
    },
    "call.make": {
        "en": ["ring {person}", "[call] {person} for me please", "phone {person} now", "get {person} on the line", "ring up {person}", "[call] the {person}", "get me the {person}", "[call] {person} please", "phone call to {person}", "[call] {person}", "[call] {person} now", "give {person} a call",
               "video call {person}", "[call] {person} for me",
               "get {person} on the phone", "put me through to {person}",
               "I need to speak to {person}"],
        "el": ["[call] {person}", "[call] {person} τώρα", "βιντεοκλήση {person}",
               "[call] {person} για μένα", "θέλω να μιλήσω {person}",
               "σύνδεσέ με με {person}"],
    },
    "navigation.route": {
        "en": ["how do i get to {location}", "how to get to {location}", "way to {location}", "fastest way to {location}", "{location}, directions", "[go] {location}", "how long to {location}",
               "is there traffic to {location}", "[go] {location} please",
               "what is the fastest way to {location}",
               "how far is {location}", "drive me to {location}"],
        "el": ["[go] {location}", "πόση ώρα θέλει {location}",
               "έχει κίνηση {location}", "ποιος είναι ο πιο γρήγορος δρόμος {location}",
               "πόσο μακριά είναι {location}", "[go] {location} παρακαλώ"],
    },
    "search.web": {
        "en": ["dont guess, look it up: {query}", "search, dont guess: {query}", "online search: {query}", "search the internet for {query}", "[find] {query}, search first", "check online: {query}", "[find] {query}, dont guess", "search online: {query}", "search first: {query}", "look it up: {query}", "[find] {query} online", "[find] {query}", "[find] {query} online",
               "[whats] {query}", "I want to know about {query}",
               "[find] information about {query}", "any results for {query}"],
        "el": ["[find] {query}", "[find] {query} στο ίντερνετ",
               "θέλω να μάθω για {query}", "πληροφορίες για {query}",
               "τι λέει το ίντερνετ για {query}"],
    },
    "translate": {
        "en": ["how do you say {phrase} in {language}",
               "translate {phrase} to {language}",
               "[whats] {phrase} in {language}", "translate {phrase}",
               "what is the {language} for {phrase}",
               "say {phrase} in {language}", "put {phrase} into {language}"],
        "el": ["πώς λέμε {phrase} στα {language}",
               "μετάφρασε {phrase} στα {language}",
               "τι σημαίνει {phrase} στα {language}", "μετάφρασε {phrase}",
               "πώς είναι το {phrase} στα {language}",
               "βάλε το {phrase} στα {language}"],
    },
    "math.calculate": {
        "en": ["[calc] {expression}", "{expression} equals what",
               "[calc] {expression} for me", "what does {expression} come to",
               "quick maths {expression}", "{expression} =",
               "give me the answer to {expression}"],
        "el": ["[calc] {expression}", "{expression} πόσο κάνει",
               "[calc] {expression} σε παρακαλώ", "πες μου το αποτέλεσμα {expression}",
               "{expression} ίσον", "κάνε την πράξη {expression}"],
    },
    "unit.convert": {
        "en": ["convert {amount} {unit_from} to {unit_to}",
               "how many {unit_to} is {amount} {unit_from}",
               "how many {unit_to} in {amount} {unit_from}",
               "{amount} {unit_from} in {unit_to}",
               "what is {amount} {unit_from} in {unit_to}",
               "turn {amount} {unit_from} into {unit_to}",
               "{amount} {unit_from} to {unit_to}",
               "give me {amount} {unit_from} as {unit_to}"],
        "el": ["μετάτρεψε {amount} {unit_from} σε {unit_to}",
               "πόσα {unit_to} είναι {amount} {unit_from}",
               "πόσα {unit_to} κάνουν {amount} {unit_from}",
               "{amount} {unit_from} σε {unit_to}",
               "κάνε {amount} {unit_from} σε {unit_to}"],
    },
    "time.query": {
        "en": ["what day is it", "what is today's date", "what day is it today", "which day is it", "what is the date", "is it monday", "what month is it", "what time is it", "[whats] the time", "what time is it in {location}",
               "what day is it", "[whats] today's date", "how many days until {date}",
               "what time is it now", "got the time", "do you have the time",
               "what is the time in {location}", "what date is it",
               "how long until {date}", "is it late"],
        "el": ["τι ώρα είναι", "τι ώρα είναι {location}", "τι μέρα έχουμε",
               "τι ημερομηνία είναι σήμερα", "πόσες μέρες μέχρι {date}",
               "ξέρεις την ώρα", "τι ώρα έχει {location}", "πόσο έχει η ώρα",
               "πόσο μένει μέχρι {date}", "είναι αργά"],
    },
    "news.query": {
        "en": ["[whats] the news", "[whats] the news about {topic}",
               "any news on {topic}", "[read] the headlines",
               "what is happening in {topic}", "latest news {topic}",
               "anything new on {topic}", "catch me up on {topic}",
               "what is going on with {topic}", "headlines about {topic}"],
        "el": ["τι νέα", "[whats] τα νέα για {topic}", "ειδήσεις για {topic}",
               "[read] τους τίτλους", "τι γίνεται με {topic}",
               "τελευταία νέα {topic}", "τι παίζει με {topic}",
               "πες μου τι γίνεται στην {topic}"],
    },
    "smalltalk.greet": {
        "en": ["hello", "hi", "hey there", "good morning", "good evening",
               "hi there", "morning", "yo", "hey assistant", "are you there",
               "evening", "hey you", "hello there", "good afternoon", "hiya"],
        "el": ["γεια", "γεια σου", "καλημέρα", "καλησπέρα", "έλα",
               "είσαι εκεί", "γεια χαρά", "καλησπέρα σου", "γεια σας",
               "με ακούς", "έλα ρε"],
    },
    "smalltalk.thanks": {
        "en": ["perfect, thanks", "great, thanks", "ok thanks", "thank you, perfect", "nice, thanks", "good, thanks", "cool thanks", "thanks", "thank you", "thanks a lot", "cheers", "perfect thanks",
               "nice one", "appreciate it", "cheers mate", "much appreciated",
               "you are a star", "great thanks", "lovely thanks"],
        "el": ["ευχαριστώ", "ευχαριστώ πολύ", "σε ευχαριστώ", "τέλεια ευχαριστώ",
               "μπράβο", "ωραία ευχαριστώ", "ευγε", "σ ευχαριστώ πολύ",
               "τα σπας", "πολύ ωραία ευχαριστώ"],
    },
    "smalltalk.bye": {
        "en": ["goodbye", "bye", "see you", "good night", "that is all",
               "we are done", "later", "bye for now", "catch you later",
               "night night", "I am off", "see you tomorrow"],
        "el": ["γεια σου", "τα λέμε", "καληνύχτα", "αυτό ήταν", "τελείωσα",
               "αντίο", "φεύγω", "τα λέμε αύριο", "καλό βράδυ", "άντε γεια"],
    },
    "assistant.capabilities": {
        "en": ["what can you do", "help", "what are your commands",
               "how do you work", "what do you know", "show me what you can do",
               "what are you good for", "list your skills", "what do you handle"],
        "el": ["τι μπορείς να κάνεις", "βοήθεια", "τι εντολές ξέρεις",
               "πώς δουλεύεις", "τι ξέρεις να κάνεις", "σε τι με βοηθάς",
               "πες μου τι κάνεις"],
    },
    "assistant.repeat": {
        "en": ["say that again", "repeat", "what did you say", "come again",
               "one more time", "sorry what", "repeat that", "again please"],
        "el": ["πες το ξανά", "επανάλαβε", "τι είπες", "ξαναπές το",
               "άλλη μια φορά", "συγγνώμη τι"],
    },
    "work.code": {
        "en": ["implement {target} so we {topic}", "write a script that {topic}", "[buildv] a script for {target}", "code {target}", "implement {target}", "add {target} to {target}", "implement {target}", "implement {target} so we {topic}", "write a script that {topic}", "{target} does {topic}, make it {topic}", "make {target} do {topic}", "add {target}", "[buildv] {target} that {topic}", "{target} is slow, [fix] it", "{target} is wrong, [fix] it", "[fix] {target}", "[fix] the bug in {target}", "[fix] {target}, it is broken",
               "{target} is broken, [fix] it", "[buildv] {target}", "[buildv] {target} for the {project}",
               "[buildv] a {target}", "can you [buildv] {target}", "{target} does not work on mobile",
               "[fix] {target} on the {project}", "[buildv] {target} in the {project}",
               "we need {target}, [buildv] it", "[fix] the error on {target}",
               "[buildv] {target} and test it", "refactor {target}", "optimize {target}",
               "[fix] whatever is wrong with {target}", "make {target} faster",
               "{target} throws an error", "[buildv] {target} like the other project"],
        "el": ["[fix] {target}", "[buildv] {target}", "[fix] το bug στο {target}", "δεν δουλεύει {target}"],
    },
    "work.review": {
        "en": ["[check] {target} went through", "[check] that {target} went through", "did {target} go through, [check]", "[check] {target} landed", "do another pass on {target}", "make a full check of {target}, what can be improved", "[check] the numbers, {target} and {target} dont align", "[check] the {target} went through", "[check] {target} again, something is off", "run the checks on {target}", "another pass on {target}", "[check] everything again", "review {target}", "[check] why {target} is wrong", "[check] {target}", "[check] {target} again", "[check] if {target} is done",
               "[check] the {project} for bugs", "[check] {target} for bugs", "[check] everything",
               "make a full [check] of {target}", "do another pass on {target}",
               "[check] that {target} works", "[check] the numbers in {target}",
               "something is wrong with {target}, [check] it", "[check] {target} before we ship",
               "run a [check] on the {project}", "[check] the logs", "[check] what changed in {target}",
               "make sure {target} is right", "[check] it did not break anything"],
        "el": ["[check] {target}", "[check] ξανά {target}", "[check] το {project}"],
    },
    "work.status": {
        "en": ["what is left to decide on {target}", "what decisions are left", "what remains to decide", "what is still open on {target}", "anything left to decide", "is {target} still running", "is the {project} still running", "is {target} running on the {project}", "still running?", "is it done?", "done with {target}?", "where is {target} at", "is {target} done", "where are we with {target}", "what is left on {target}",
               "status of {target}", "did {target} finish", "is {target} still running",
               "how far along is {target}", "what is the state of the {project}",
               "give me the status", "what is left to decide", "what is pending",
               "are we done with {target}", "any progress on {target}", "how is {target} going",
               "is the {project} ready", "what did you finish"],
        "el": ["τελείωσε {target}", "πού είμαστε με {target}", "τι μένει για {target}"],
    },
    "work.research": {
        "en": ["[explain] what {topic} is", "what is {topic}", "what are {topic}", "why is {target} {topic}", "why does {target} show {topic}", "is {topic} useful for the {project}", "is {topic} useful", "should we {topic} or {topic}", "give me {topic} from old to new", "give me a list of {topic} close to {topic}", "what do you think about {topic}", "[explain] {topic} vs {topic}", "is {topic} a good idea", "does {topic} make sense for us", "[explain] {topic}", "[explain] {topic} to me", "[explain] the difference between {topic} and {topic}",
               "should we use {topic} or {topic}", "is {topic} worth it", "why is {topic} happening",
               "[explain] what {topic} is", "give me options for {topic}", "what do you recommend for {topic}",
               "research {topic}", "[explain] how {topic} works", "pros and cons of {topic}",
               "which is better for us, {topic} or {topic}", "what are the alternatives to {topic}",
               "give me a list of {topic}", "is it a good idea to {topic}"],
        "el": ["[explain] {topic}", "τι είναι {topic}", "αξίζει {topic}"],
    },
    "work.write": {
        "en": ["email {person} that {content}", "write to {person} that {content}", "[draft] an email to {person} that {content}", "tell {person} by email that {content}", "[draft] an email to {person} that {content}", "[draft] to {person} that {content}", "[draft] {person} saying {content}", "email {person} that {content}", "answer {person} that {content}", "reply to {person}: {content}", "[draft] an email to {person} about {topic}", "[draft] a message for {person}",
               "[draft] a shorter version", "[draft] a proposal for {topic}",
               "[draft] the post about {topic}", "[draft] {person} that {content}",
               "[draft] a document with your findings", "[draft] this in greek",
               "[draft] a reply to {person}", "[draft] the copy for {target}",
               "[draft] an sms to {person}", "[draft] a summary of {topic}",
               "[draft] it more formal", "[draft] a cover letter for {topic}",
               "put this in an md file", "[draft] the invoice email to {person}"],
        "el": ["[draft] ένα email σε {person}", "[draft] μια πρόταση για {topic}", "[draft] το πιο σύντομα"],
    },
    "work.files": {
        "en": ["[delete] {target} and {target}", "[delete] the temp folders and {target}", "clear out {target} and {target}", "move {target} to {target}", "zip {target} and put it on {target}", "[delete] {target} and {target} and {target}", "put {target} on {target}", "copy {target} to {target}", "move {target}", "archive {target}", "[delete] {target}", "[delete] {target} and {target}", "[delete] the temp files",
               "[delete] {target} completely", "move {target} to {target}", "zip {target}",
               "what is taking space on {target}", "clean up {target}", "free up space on {target}",
               "[delete] the old installers", "find {target} on the disk", "rename {target}",
               "copy {target} to the backup", "[delete] the cache", "how big is {target}",
               "[delete] everything related to {target}", "organize {target}"],
        "el": ["[delete] {target}", "καθάρισε {target}", "μετακίνησε {target}"],
    },
    "work.ops": {
        "en": ["stop {target} and [restartv] with {topic}", "[restartv] {target} with {topic}", "back up {target} before you touch anything", "back up {target}", "[restartv] the training with {topic}", "stop the current {target}", "[deploy] {target} now", "[restartv] it", "[deploy]", "[deploy] {target}", "[deploy] the {project}", "[restartv] the server",
               "[restartv] {target}", "[restartv] the training", "[restartv] the bot",
               "push {target} live", "[restartv] the training with {target}", "back up {target} first",
               "[deploy] it to production", "[restartv] the service on the pi", "renew the ssl on {target}",
               "[restartv] {target} on the other pc", "take {target} offline", "[deploy] and [check] it"],
        "el": ["[deploy]", "[restartv] τον server", "[restartv] {target}"],
    },
    "work.business": {
        "en": ["how much did we make {date}", "what did we earn {date}", "revenue for {date}", "how much came in {date}", "the client wants {topic}, what do we do", "the client asks for {topic}", "what do we tell the client about {topic}", "how do we answer the client on {topic}", "is the {project} worth it at {topic}", "is {topic} worth it with these fees", "does {topic} pay off", "how much is the {project} making", "prepare a quote for {topic}", "what should i charge for {topic}", "price {topic}",
               "the client wants {topic}, what do we do", "send the invoice for {topic}",
               "how much did we make on {topic}", "is {topic} worth it at that price",
               "make an offer for {topic}", "what is the budget for {topic}",
               "how do we handle the client on {topic}", "estimate {topic}",
               "how many hours for {topic}", "give me a pricing for {topic}",
               "the client did not pay for {topic}", "is {topic} profitable"],
        "el": ["ετοίμασε προσφορά για {topic}", "πόσο να χρεώσω για {topic}", "τιμολόγιο για {topic}"],
    },
    "rule.set": {
        "en": ["remember that i {fact}", "note that i {fact}", "i {fact}, keep that in mind", "for your information i {fact}", "keep in mind that i {fact}", "stop {rule}", "quit {rule}", "no more {rule}", "enough {rule}", "you keep {rule}, stop it", "remember that {content}", "remember that i {content}", "note that i {content}", "keep in mind i {content}", "[never] {rule} again", "[always] {rule} from now on", "i {content}, remember it", "[never] {rule}", "[always] {rule}", "[never] do that again",
               "[always] {rule}, no exceptions", "rule: {rule}", "remember: {rule}",
               "i told you, {rule}", "i dont want you to {rule}", "stop {rule}",
               "only {rule} from now on", "[never] {rule} unless i say so",
               "[always] {rule} before you answer", "keep in mind that {rule}",
               "note for the future: {rule}", "you must {rule}", "i want you to {rule}"],
        "el": ["[never] {rule}", "[always] {rule}", "κανόνας: {rule}", "να θυμάσαι ότι {rule}"],
    },
    "assistant.cancel": {
        "en": ["forget about it", "drop it", "never mind that", "scrap that", "cancel that", "forget what i said", "leave it, never mind", "nah, forget it", "cancel", "never mind", "forget it", "stop", "no don't",
               "abort", "leave it", "as you were", "ignore that", "scratch that"],
        "el": ["ακύρωση", "άσε το", "ξέχνα το", "σταμάτα", "μη", "άκυρο",
               "άσ το", "τίποτα", "ξέχνα ότι είπα"],
    },
}

OOS = {
    "en": ["what is the meaning of life", "write me a poem about the sea",
           "write me a song about the ocean", "write a short story for my kid",
           "explain quantum physics", "who was the first president of France",
           "tell me a long story about dragons", "do you love me",
           "summarize the theory of relativity", "what happens after we die",
           "give me investment advice for my portfolio", "diagnose my back pain",
           "write a python script that scrapes a website", "are you conscious",
           "solve this differential equation for me", "who will win the election",
           "explain the causes of world war one", "what should I name my baby",
           "review my business plan", "translate this whole document for me",
           "compose an email to my whole team about layoffs",
           "what do you think about politics", "tell me a joke about physics",
           "how does a nuclear reactor work", "teach me to play the guitar",
           "why is the sky blue", "who invented the telephone",
           "write my cv", "debug this javascript for me", "draw me a picture",
           "write me a sonnet about the moon", "write a haiku about rain", "compose a poem for my mother",
           "write lyrics for a love song", "write me a short story about a dragon", "write a fairy tale",
           "write a rap about coffee", "write a limerick", "make up a bedtime story", "write a poem about athens",
           "write me a song about the sea", "invent a story for my kid", "write a joke about cats",
           "write an essay on freedom", "write a speech for a wedding",
           "asdf asdf", "blah blah blah", "aaaaa", "hmm", "???", "qwerty",
           "zxcvbn", "test test test", "lorem ipsum dolor",
           "the quick brown fox jumps", "banana banana banana", "1234 5678",
           "xyz abc", "wubba lubba dub dub"],
    "el": ["ποιο είναι το νόημα της ζωής", "γράψε μου ένα ποίημα",
           "γράψε μου ένα τραγούδι", "γράψε μου μια ιστορία",
           "εξήγησέ μου την κβαντική φυσική", "πες μου μια ιστορία",
           "τι γίνεται μετά τον θάνατο", "δώσε μου επενδυτικές συμβουλές",
           "τι έχω στην πλάτη μου", "γράψε μου κώδικα σε python",
           "έχεις συνείδηση", "ποιος θα κερδίσει τις εκλογές",
           "εξήγησε τον δεύτερο παγκόσμιο πόλεμο", "τι όνομα να βάλω στο μωρό",
           "γράψε μου το βιογραφικό", "πες μου ένα αστείο",
           "πώς δουλεύει ένας πυρηνικός αντιδραστήρας", "μάθε μου κιθάρα",
           "γιατί ο ουρανός είναι γαλάζιος", "τι γνώμη έχεις για την πολιτική",
           "φτιάξε μου μια ζωγραφιά", "διόρθωσε τον κώδικά μου",
           "γράψε μου ένα σονέτο", "γράψε ένα ποίημα για τη μάνα μου", "γράψε στίχους για τραγούδι",
           "γράψε μου ένα παραμύθι", "γράψε ένα ανέκδοτο", "φτιάξε μια ιστορία για το παιδί",
           "ααααα", "μπλα μπλα", "δεν ξέρω", "τεστ τεστ", "ασδφ ασδφ",
           "1234 5678", "λαλαλα", "κάτι τυχαίο"],
}
